# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37df01e5723183b376578d76796bbd11b27e9d4bd3d824260221c190a6927ba2c74796de77d63f55f6c7acc8bbc0d3438df4eee1f975e32a783538d499177533

test:
  secret_key_base: e4110b8f5de29c89de80ee3a37cc64d0dc30988921a6d59535a501f872606d9ce196ec036da0ab33ebd347cf23323d9f3c0f23162f0c2db1fa121ca0a4eb88ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
