# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c7d38b876aaa40c91ed833decc1f6e588443acd853824c8a98b67d8de0ea8fbe3aaf4862b7c64c40a32b7bb60b4109a88ba56d948cd326830092e66553eb5c3

test:
  secret_key_base: 99a169e703ac0a3ef5322250d132c6ac95ac929a5d55ee88e584e349d0cc074f998de6f65b32a4400b52e286d16cad47d21ff9ad92cdf98c759653c840d02d2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
